### ISSUE TITLE
How can anyone be creative if they copy?

### ISSUE THREAD

**Issue by MichaelNecio** [Quinny/60-454-Design-and-Analysis-of-Algorithms#1]
Also it'd be a good idea to include the original assignment questions and solutions because Tsin takes those down.
[Soln1.pdf](https://github.com/Quinny/60-454-Design-and-Analysis-of-Algorithms/files/917954/Soln1.pdf)
[Soln2.pdf](https://github.com/Quinny/60-454-Design-and-Analysis-of-Algorithms/files/917951/Soln2.pdf)
[Soln3.pdf](https://github.com/Quinny/60-454-Design-and-Analysis-of-Algorithms/files/917952/Soln3.pdf)
[Soln4.pdf](https://github.com/Quinny/60-454-Design-and-Analysis-of-Algorithms/files/917953/Soln4.pdf)

**Comment by Quinny** [comment]
Added.
